Authentication
nfqakademija/kambariokas pull request #3
Opened 2019-04-24 11:08 UTC by domantax

Authentication feature:
registration - /register
login - /login
logout - /logout

2019-04-24 11:33 UTC, chyzas requested changes
viskas ok tik aptvarkyt koda ir butinai sutvarkyt vertimus

2019-04-24 11:33 UTC, chyzas commented on assets/img/images.js
> +require('./icons/github.svg');
kam sitas? jei loginui tai nereik :) fb ir google pagrindiniai

2019-04-24 11:33 UTC, chyzas commented on src/Controller/RegistrationController.php
> +
tarpu nereik

2019-04-24 11:33 UTC, chyzas commented on src/Controller/RegistrationController.php
> +        if ($authenticated) {
if ($this->isGranted('ROLE_USER'))

2019-04-24 11:33 UTC, chyzas commented on src/Controller/SecurityController.php
> +
istrint tapus visur

2019-04-24 11:33 UTC, chyzas commented on src/Entity/User.php
> + * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
istrink sita message, man atrodo turetu but pagal locale verciamas. ir siaip visur geriau naudot translation 
https://symfony.com/doc/current/translation.html

2019-04-24 11:33 UTC, chyzas commented on src/Form/RegistrationFormType.php
> +                'message' => 'Please enter a password',
vertimai, palik defaultinius symfonio vertimus. t.y. istrink message ir visur kitur taip pat

2019-04-24 11:33 UTC, chyzas commented on src/Security/LoginFormAuthenticator.php
> +
tarpai tarpai :)

2019-04-24 11:33 UTC, chyzas commented on src/Security/LoginFormAuthenticator.php
> +
pravalyt tarpus

2019-04-24 11:33 UTC, chyzas commented on templates/authentication.html.twig
> +                    Pavadinimas
https://symfony.com/doc/current/translation.html ir visur turi but translated

2019-04-24 11:33 UTC, chyzas commented on templates/home/index.html.twig
> +    <a href="{{ path('logout') }}">Logout</a>
vertimai

2019-04-24 11:33 UTC, chyzas commented on templates/security/login.html.twig
> +{% block title %}Log in!{% endblock %}
vertimai, vienur lietuviskai kitur angliskai!

2019-04-24 22:15 UTC, domantax commented on src/Entity/User.php
> + * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
Sita palikau, ir su translatoriu isverciau. Nezinau ar gerai :)

2019-04-25 05:21 UTC, chyzas approved these changes

2019-04-25 05:22 UTC, chyzas commented
susitvarkyk konliktus ir mergink

2019-04-25 10:17 UTC, merged